<?xml version="1.0"?>
<package format="3">
  <name>gui_py</name>
  <version>0.0.0</version>
  <description>ROS2 GUI package for teleoperation, SLAM control, and sensor management.</description>
  <maintainer email="todo@todo.com">relayrobot</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <exec_depend>python3-tk</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
